---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  url: ssh://git@github.com/sydorovdmytro/homelab_secrets
  ref:
    branch: main
  secretRef:
    name: homelab-secrets
  ignore: |
    - '.sops.yaml'
    - 'ssh/'
    - 'README.md'

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: homelab-secrets
  path: ./
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
