apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal
  namespace: metallb
spec:
  addresses:
    - 10.20.0.240/29
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal
  namespace: metallb
spec:
  ipAddressPools:
    - internal
