apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: configs
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - cert-manager/clusterissuer.yaml
